"""Cross-array comparison for N=4, N=6, N=8 period scan outputs.

This script reads summary and point-probe CSV files generated by completed full scans,
validates input integrity, writes comparison CSV tables, and generates objective
comparison figures.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

OUTPUT_DIR = Path("outputs")
FIGURE_DIR = Path("figures")
ARRAY_SIZES = (4, 6, 8)
EXPECTED_PERIODS = np.round(np.arange(0.90, 2.00 + 1e-12, 0.01), 2)
SUMMARY_REQUIRED_COLUMNS = [
    "period",
    "array_size",
    "mesh_level",
    "center_mean_abs",
    "center_max_abs",
    "front_abs",
    "rear_abs",
    "S_rear_front",
]
POINT_REQUIRED_COLUMNS = ["probe", "period", "array_size", "mesh_level", "total_abs"]
REQUIRED_PROBES = ["P0", "P1", "P2", "P3", "P4", "front", "rear"]
CENTER_PROBES = ["P0", "P1", "P2", "P3", "P4"]
KEY_METRICS = [
    "center_mean_abs",
    "center_max_abs",
    "center_max_to_mean_ratio",
    "front_abs",
    "rear_abs",
    "S_rear_front",
]
ANOMALY_LOW = 0.90
ANOMALY_HIGH = 0.93


def input_paths(array_size: int) -> tuple[Path, Path]:
    summary = OUTPUT_DIR / f"N{array_size}_period_scan_summary_0p90_2p00.csv"
    points = OUTPUT_DIR / f"N{array_size}_period_scan_point_probes_0p90_2p00.csv"
    return summary, points


def check_required_columns(df: pd.DataFrame, required: list[str], label: str) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{label} 缺少必要列: {missing}")


def period_sequence_ok(periods: pd.Series) -> bool:
    numeric_periods = pd.to_numeric(periods, errors="coerce").round(2)
    unique_sorted = np.sort(numeric_periods.unique())
    return (
        len(unique_sorted) == len(EXPECTED_PERIODS)
        and np.allclose(unique_sorted, EXPECTED_PERIODS, atol=1e-12, rtol=0.0)
    )


def check_peak_flags(period: float) -> tuple[bool, bool]:
    peak_at_boundary = bool(np.isclose(period, 0.90) or np.isclose(period, 2.00))
    near_anomaly_interval = bool(ANOMALY_LOW <= period <= ANOMALY_HIGH)
    return peak_at_boundary, near_anomaly_interval


def annotate_anomaly_interval(ax: plt.Axes) -> None:
    ax.axvspan(ANOMALY_LOW, ANOMALY_HIGH, color="gray", alpha=0.15, label="anomaly-check interval")


def load_and_validate() -> tuple[dict[int, pd.DataFrame], dict[int, pd.DataFrame]]:
    summary_data: dict[int, pd.DataFrame] = {}
    point_data: dict[int, pd.DataFrame] = {}

    paths = [p for n in ARRAY_SIZES for p in input_paths(n)]
    missing_files = [str(p) for p in paths if not p.exists()]
    if missing_files:
        raise ValueError("输入文件缺失:\n" + "\n".join(missing_files))

    for n in ARRAY_SIZES:
        summary_path, points_path = input_paths(n)
        summary_df = pd.read_csv(summary_path)
        points_df = pd.read_csv(points_path)

        check_required_columns(summary_df, SUMMARY_REQUIRED_COLUMNS, f"N{n} summary")
        check_required_columns(points_df, POINT_REQUIRED_COLUMNS, f"N{n} point_probes")

        summary_df["period"] = pd.to_numeric(summary_df["period"], errors="coerce").round(2)
        points_df["period"] = pd.to_numeric(points_df["period"], errors="coerce").round(2)

        if not period_sequence_ok(summary_df["period"]):
            raise ValueError(f"N{n} summary period 非 0.90–2.00, 步长 0.01, 共 111 点")

        probes = sorted(points_df["probe"].dropna().astype(str).unique().tolist())
        missing_probes = [p for p in REQUIRED_PROBES if p not in probes]
        if missing_probes:
            raise ValueError(f"N{n} point_probes 缺少探针: {missing_probes}")

        summary_data[n] = summary_df.copy()
        point_data[n] = points_df.copy()

    base_periods = np.sort(summary_data[ARRAY_SIZES[0]]["period"].unique())
    for n in ARRAY_SIZES[1:]:
        cur_periods = np.sort(summary_data[n]["period"].unique())
        if not np.array_equal(base_periods, cur_periods):
            raise ValueError(f"N{ARRAY_SIZES[0]} 与 N{n} summary period 不一致")

    summary_cols = [summary_data[n].columns.tolist() for n in ARRAY_SIZES]
    if not (summary_cols[0] == summary_cols[1] == summary_cols[2]):
        raise ValueError("N4/N6/N8 summary 列名不一致")

    point_cols = [point_data[n].columns.tolist() for n in ARRAY_SIZES]
    if not (point_cols[0] == point_cols[1] == point_cols[2]):
        raise ValueError("N4/N6/N8 point_probes 列名不一致")

    return summary_data, point_data


def build_outputs(summary_data: dict[int, pd.DataFrame], point_data: dict[int, pd.DataFrame]) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    key_rows: list[pd.DataFrame] = []
    peak_rows: list[dict[str, object]] = []
    probe_peak_rows: list[dict[str, object]] = []

    for n in ARRAY_SIZES:
        sdf = summary_data[n].copy()
        sdf["center_max_to_mean_ratio"] = sdf["center_max_abs"] / sdf["center_mean_abs"]

        key_df = sdf[
            [
                "array_size",
                "period",
                "center_mean_abs",
                "center_max_abs",
                "center_max_to_mean_ratio",
                "front_abs",
                "rear_abs",
                "S_rear_front",
            ]
        ].copy()
        key_rows.append(key_df)

        for metric in KEY_METRICS:
            idx = key_df[metric].idxmax()
            peak_period = float(key_df.loc[idx, "period"])
            peak_value = float(key_df.loc[idx, metric])
            peak_at_boundary, near_anomaly_interval = check_peak_flags(peak_period)
            peak_rows.append(
                {
                    "array_size": int(key_df.loc[idx, "array_size"]),
                    "metric": metric,
                    "peak_period": peak_period,
                    "peak_value": peak_value,
                    "peak_at_boundary": peak_at_boundary,
                    "near_anomaly_interval": near_anomaly_interval,
                }
            )

        pdf = point_data[n].copy()
        center = pdf[pdf["probe"].isin(CENTER_PROBES)]
        for probe in CENTER_PROBES:
            p = center[center["probe"] == probe]
            idx = p["total_abs"].idxmax()
            peak_period = float(p.loc[idx, "period"])
            peak_value = float(p.loc[idx, "total_abs"])
            peak_at_boundary, near_anomaly_interval = check_peak_flags(peak_period)
            probe_peak_rows.append(
                {
                    "array_size": int(p.loc[idx, "array_size"]),
                    "probe": probe,
                    "peak_period": peak_period,
                    "peak_value": peak_value,
                    "peak_at_boundary": peak_at_boundary,
                    "near_anomaly_interval": near_anomaly_interval,
                }
            )

    key_metrics = pd.concat(key_rows, ignore_index=True)
    peak_metrics = pd.DataFrame(peak_rows)
    center_probe_peaks = pd.DataFrame(probe_peak_rows)
    return key_metrics, peak_metrics, center_probe_peaks




def build_summary_table_for_paper(peak_metrics: pd.DataFrame, center_probe_peaks: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for n in ARRAY_SIZES:
        row: dict[str, object] = {"array_size": n}
        boundary_count = 0

        for metric in KEY_METRICS:
            rec = peak_metrics[(peak_metrics["array_size"] == n) & (peak_metrics["metric"] == metric)].iloc[0]
            row[f"{metric}_peak_period"] = float(rec["peak_period"])
            row[f"{metric}_peak_value"] = float(rec["peak_value"])
            row[f"{metric}_peak_at_boundary"] = bool(rec["peak_at_boundary"])
            row[f"{metric}_near_anomaly_interval"] = bool(rec["near_anomaly_interval"])
            boundary_count += int(bool(rec["peak_at_boundary"]))

        for probe in CENTER_PROBES:
            rec = center_probe_peaks[(center_probe_peaks["array_size"] == n) & (center_probe_peaks["probe"] == probe)].iloc[0]
            row[f"{probe}_peak_period"] = float(rec["peak_period"])
            row[f"{probe}_peak_value"] = float(rec["peak_value"])
            row[f"{probe}_peak_at_boundary"] = bool(rec["peak_at_boundary"])
            row[f"{probe}_near_anomaly_interval"] = bool(rec["near_anomaly_interval"])
            boundary_count += int(bool(rec["peak_at_boundary"]))

        row["boundary_peak_flag_count"] = boundary_count
        rows.append(row)

    return pd.DataFrame(rows)

def create_plots(key_metrics: pd.DataFrame, center_probe_peaks: pd.DataFrame) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8, 5))
    for n in ARRAY_SIZES:
        d = key_metrics[key_metrics["array_size"] == n]
        ax.plot(d["period"], d["center_mean_abs"], label=f"N={n}")
    annotate_anomaly_interval(ax)
    ax.set_title("center_mean_abs comparison")
    ax.set_xlabel("Period (s)")
    ax.set_ylabel("center_mean_abs")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_center_mean_comparison.png", dpi=300)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 5))
    for n in ARRAY_SIZES:
        d = key_metrics[key_metrics["array_size"] == n]
        ax.plot(d["period"], d["center_max_abs"], label=f"N={n}")
    annotate_anomaly_interval(ax)
    ax.set_title("center_max_abs comparison")
    ax.set_xlabel("Period (s)")
    ax.set_ylabel("center_max_abs")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_center_max_comparison.png", dpi=300)
    plt.close(fig)

    fig, axes = plt.subplots(3, 1, figsize=(8, 10), sharex=True)
    fields = ["front_abs", "rear_abs", "S_rear_front"]
    titles = ["front_abs comparison", "rear_abs comparison", "S_rear_front comparison (transmission-like indicator)"]
    for ax, field, title in zip(axes, fields, titles):
        for n in ARRAY_SIZES:
            d = key_metrics[key_metrics["array_size"] == n]
            ax.plot(d["period"], d[field], label=f"N={n}")
        annotate_anomaly_interval(ax)
        ax.set_title(title)
        ax.set_ylabel(field)
        ax.legend()
    axes[-1].set_xlabel("Period (s)")
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_front_rear_S_comparison.png", dpi=300)
    plt.close(fig)

    pivot = center_probe_peaks.pivot(index="probe", columns="array_size", values="peak_value").reindex(CENTER_PROBES)
    x = np.arange(len(CENTER_PROBES))
    width = 0.25
    fig, ax = plt.subplots(figsize=(8, 5))
    for i, n in enumerate(ARRAY_SIZES):
        ax.bar(x + (i - 1) * width, pivot[n].to_numpy(), width=width, label=f"N={n}")
    ax.set_xticks(x)
    ax.set_xticklabels(CENTER_PROBES)
    ax.set_xlabel("probe")
    ax.set_ylabel("peak total_abs")
    ax.set_title("P0-P4 peak comparison across N=4/6/8")
    ax.legend(title="array_size")
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_center_probe_peak_comparison.png", dpi=300)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 5))
    for n in ARRAY_SIZES:
        d = key_metrics[key_metrics["array_size"] == n]
        ax.plot(d["period"], d["center_max_to_mean_ratio"], label=f"N={n}")
    annotate_anomaly_interval(ax)
    ax.set_title("center_max_to_mean_ratio comparison")
    ax.set_xlabel("Period (s)")
    ax.set_ylabel("center_max_to_mean_ratio")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_center_max_to_mean_ratio_comparison.png", dpi=300)
    plt.close(fig)

    pp = center_probe_peaks.pivot(index="probe", columns="array_size", values="peak_period").reindex(CENTER_PROBES)
    boundary = center_probe_peaks.pivot(index="probe", columns="array_size", values="peak_at_boundary").reindex(CENTER_PROBES)
    fig, ax = plt.subplots(figsize=(8, 5))
    for i, n in enumerate(ARRAY_SIZES):
        vals = pp[n].to_numpy()
        xloc = x + (i - 1) * width
        bars = ax.bar(xloc, vals, width=width, label=f"N={n}")
        for j, b in enumerate(bars):
            if bool(boundary.iloc[j][n]):
                ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 0.01, "*", ha="center", va="bottom", fontsize=12)
    ax.set_xticks(x)
    ax.set_xticklabels(CENTER_PROBES)
    ax.set_xlabel("probe")
    ax.set_ylabel("peak_period")
    ax.set_title("P0-P4 peak period comparison across N=4/6/8")
    ax.legend(title="array_size")
    ax.text(0.01, 0.98, "* = boundary peak", transform=ax.transAxes, va="top", ha="left")
    fig.tight_layout()
    fig.savefig(FIGURE_DIR / "N468_center_probe_peak_period_comparison.png", dpi=300)
    plt.close(fig)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    summary_data, point_data = load_and_validate()
    key_metrics, peak_metrics, center_probe = build_outputs(summary_data, point_data)
    summary_table = build_summary_table_for_paper(peak_metrics, center_probe)

    key_path = OUTPUT_DIR / "N468_key_metrics_comparison.csv"
    peak_path = OUTPUT_DIR / "N468_peak_periods_comparison.csv"
    center_path = OUTPUT_DIR / "N468_center_probe_comparison.csv"
    summary_table_path = OUTPUT_DIR / "N468_summary_table_for_paper.csv"

    key_metrics.to_csv(key_path, index=False)
    peak_metrics.to_csv(peak_path, index=False)
    center_probe.to_csv(center_path, index=False)
    summary_table.to_csv(summary_table_path, index=False)

    create_plots(key_metrics, center_probe)

    print("输入文件检查通过。")
    print("输出文件清单:")
    outputs = [
        key_path,
        peak_path,
        center_path,
        FIGURE_DIR / "N468_center_mean_comparison.png",
        FIGURE_DIR / "N468_center_max_comparison.png",
        FIGURE_DIR / "N468_front_rear_S_comparison.png",
        FIGURE_DIR / "N468_center_probe_peak_comparison.png",
        FIGURE_DIR / "N468_center_max_to_mean_ratio_comparison.png",
        FIGURE_DIR / "N468_center_probe_peak_period_comparison.png",
        summary_table_path,
    ]
    for out in outputs:
        print(f"- {out}")

    print("\nN468_peak_periods_comparison.csv 内容:")
    print(peak_metrics.to_string(index=False))

    print("\nN468_center_probe_comparison.csv 内容:")
    print(center_probe.to_string(index=False))

    print("\nN468_summary_table_for_paper.csv 内容:")
    print(summary_table.to_string(index=False))


if __name__ == "__main__":
    main()
